### ISSUE TITLE
Hello author, do you have a download link for the dataset?

### ISSUE THREAD

**Issue by hshc123** [soumyasj/NewsVideoQA#1]

**Comment by soumyasj** [comment]
Hi!

The link is already present in the readme of this repository. You will have to register in the RRC website to download the dataset. (Adding link here again: https://rrc.cvc.uab.es/?ch=24&com=downloads)

Hope this helps :)

**Comment by Batwho** [comment]
Hello,

I have registered and it seems have error, also with this link: https://cvit.iiit.ac.in/images/datasets/newvideosQA/newsvideoQA.tar.gz
Could you please fix it?
